In [1]:
import matplotlib.pyplot as plot
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
train = pd.read_csv('../data/in/train.csv', delimiter=';')
test = pd.read_csv('../data/in/test.csv', delimiter=';')

In [3]:
train.columns

Index(['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio'],
      dtype='object')

In [4]:
train['age2'] = train.age/365.25
test['age2'] = test.age/365.25
train['age2'].describe(), test['age2'].describe()

(count    70000.000000
 mean        53.302850
 std          6.754967
 min         29.563313
 25%         48.361396
 50%         53.943874
 75%         58.390144
 max         64.922656
 Name: age2, dtype: float64, count    30000.000000
 mean        53.266334
 std          6.783959
 min         24.271047
 25%         48.344969
 50%         53.919233
 75%         58.370979
 max         64.900753
 Name: age2, dtype: float64)

In [5]:
train.ix[train.ap_hi < 0, 'ap_hi'] *= -1
train.ix[train.ap_hi < 50, 'ap_hi'] *= 10
train.ix[train.ap_hi > 5000, 'ap_hi'] *= 1e-2
train.ix[train.ap_hi > 500, 'ap_hi'] *= 1e-1

test.ix[1929, ['ap_hi', 'ap_lo']] = 110, 99
test.ix[15510, ['ap_hi', 'ap_lo']] = 120, 88
test.ix[12852, ['ap_hi', 'ap_lo']] = 130, np.NaN

test.ix[test.ap_hi < 0, 'ap_hi'] *= -1
test.ix[(test.ap_hi < 25).values, 'ap_hi'] *= 10
test.ix[test.ap_hi > 5000, 'ap_hi'] *= 1e-2
test.ix[test.ap_hi > 500, 'ap_hi'] *= 1e-1

train.ix[8757, ['ap_hi', 'ap_lo']] = 120, 88
train.ix[2014, ['ap_hi', 'ap_lo']] = 90, 60
train.ix[17381, ['ap_hi', 'ap_lo']] = 130, 80
train.ix[31783, ['ap_hi', 'ap_lo']] = 90, 70
train.ix[38370, ['ap_hi', 'ap_lo']] = 140, 80
train.ix[41505, ['ap_hi', 'ap_lo']] = 80, 60
train.ix[42397, ['ap_hi', 'ap_lo']] = 90, 60
train.ix[43922, ['ap_hi', 'ap_lo']] = 100, 80
train.ix[63787, ['ap_hi', 'ap_lo']] = 110, 70
train.ix[68663, ['ap_hi', 'ap_lo']] = 90, 60

train.ix[train.ap_lo < 0, 'ap_lo'] *= -1
train.ix[train.ap_lo > 2500, 'ap_lo'] *= 1e-2
train.ix[train.ap_lo > 250, 'ap_lo'] *= 1e-1
train.ix[train.ap_lo < 10, 'ap_lo'] *= 10
train.ix[train.ap_lo < 10, 'ap_lo'] = np.NAN
train[(train.ap_lo < 49).values * (train.cardio==0).values] = np.NAN

test.ix[test.ap_lo < 0, 'ap_lo'] *= -1
test.ix[test.ap_lo > 2500, 'ap_lo'] *= 1e-2
test.ix[test.ap_lo > 250, 'ap_lo'] *= 1e-1
test.ix[test.ap_lo < 10, 'ap_lo'] *= 10

x = train.ix[train.ap_lo >= train.ap_hi, ['ap_lo', 'ap_hi']]
x.columns = ['ap hi', 'ap lo']
train.ix[train.ap_lo >= train.ap_hi, ['ap_hi', 'ap_lo']] = x

train.ix[train.height < 90, 'height'] += 100
test.ix[test.height < 90, 'height'] += 100

In [7]:
test[(test.ap_hi > 250).values]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,age2
303,1079,22571,2,170,74.0,400.0,60.0,1,1,0,0,1,61.79603

In [16]:
train[(train.ap_lo < 49).values]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age2
418,594.0,16658.0,1.0,157.0,72.0,150.0,30.0,1.0,1.0,0.0,0.0,1.0,1.0,45.607118
507,728.0,16822.0,1.0,165.0,64.0,140.0,40.0,1.0,1.0,0.0,0.0,1.0,1.0,46.056126
6737,9610.0,16705.0,1.0,156.0,61.0,150.0,10.0,1.0,1.0,0.0,0.0,0.0,1.0,45.735797
10106,14410.0,18334.0,1.0,152.0,50.0,150.0,10.0,3.0,1.0,0.0,0.0,1.0,1.0,50.195756
10645,15213.0,20343.0,1.0,160.0,65.0,130.0,40.0,3.0,1.0,0.0,0.0,0.0,1.0,55.696099
11820,16884.0,18171.0,1.0,169.0,69.0,128.0,20.0,1.0,1.0,0.0,0.0,1.0,1.0,49.749487
12997,18534.0,22627.0,1.0,158.0,67.0,140.0,40.0,1.0,1.0,0.0,0.0,1.0,1.0,61.949350
17552,25074.0,15302.0,1.0,159.0,56.0,130.0,40.0,1.0,1.0,0.0,0.0,1.0,1.0,41.894593
17754,25368.0,22433.0,1.0,150.0,82.0,140.0,40.0,2.0,1.0,0.0,0.0,1.0,1.0,61.418207
18958,27069.0,17452.0,2.0,170.0,62.0,110.0,20.0,1.0,1.0,0.0,0.0,1.0,1.0,47.780972
22380,31965.0,16120.0,2.0,170.0,66.0,120.0,20.0,1.0,1.0,0.0,0.0,1.0,1.0,44.134155
24757,35356.0,20432.0,1.0,168.0,68.0,120.0,20.0,1.0,1.0,0.0,0.0,1.0,1.0,55.939767
26513,37874.0,18984.0,1.0,157.0,69.0,160.0,10.0,3.0,1.0,0.0,0.0,1.0,1.0,51.975359
28401,40612.0,21719.0,2.0,172.0,64.0,150.0,40.0,1.0,2.0,0.0,0.0,1.0,1.0,59.463381
33262,47533.0,20414.0,2.0,174.0,91.0,120.0,30.0,1.0,1.0,0.0,0.0,1.0,1.0,55.890486
36958,52813.0,18237.0,1.0,171.0,82.0,160.0,30.0,1.0,1.0,0.0,0.0,0.0,1.0,49.930185
39896,57023.0,18167.0,1.0,177.0,59.0,120.0,20.0,2.0,2.0,0.0,0.0,1.0,1.0,49.738535
42446,60635.0,22645.0,2.0,166.0,98.0,130.0,40.0,1.0,1.0,0.0,0.0,1.0,1.0,61.998631
43137,61623.0,21932.0,1.0,170.0,120.0,160.0,40.0,3.0,3.0,0.0,0.0,1.0,1.0,60.046543
43307,61874.0,22718.0,1.0,151.0,58.0,170.0,10.0,3.0,1.0,0.0,0.0,1.0,1.0,62.198494
44609,63710.0,22433.0,2.0,165.0,65.0,130.0,20.0,1.0,1.0,0.0,0.0,1.0,1.0,61.418207
51151,72965.0,21845.0,1.0,150.0,79.0,150.0,40.0,2.0,1.0,0.0,0.0,1.0,1.0,59.808350
51158,72974.0,17371.0,1.0,160.0,68.0,160.0,45.0,1.0,1.0,0.0,0.0,1.0,1.0,47.559206
52851,75399.0,17770.0,2.0,164.0,64.0,240.0,20.0,3.0,1.0,0.0,0.0,1.0,1.0,48.651608
56927,81260.0,18336.0,1.0,155.0,76.0,70.0,15.0,1.0,1.0,0.0,1.0,1.0,1.0,50.201232
57641,82269.0,20627.0,1.0,157.0,76.0,180.0,20.0,1.0,1.0,0.0,0.0,1.0,1.0,56.473648
68223,97439.0,18809.0,2.0,173.0,100.0,130.0,20.0,1.0,1.0,0.0,0.0,1.0,1.0,51.496235

In [10]:
test[test.ap_lo < 50]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,age2
1114,3828,14653,2,165,74.0,120.0,40.0,2,1,1,0,None,40.117728
1626,5559,17538,2,167,72.0,120.0,30.0,1,1,0,0,1,48.016427
2371,8018,21291,1,161,88.0,120.0,30.0,2,1,0,0,1,58.291581
2443,8272,21060,1,165,72.0,160.0,10.0,3,3,None,0,1,57.659138
3160,10586,17447,1,160,75.0,170.0,41.0,1,1,0,0,1,47.767283
3515,11745,20874,1,158,79.0,130.0,40.0,1,1,0,0,1,57.149897
6294,20962,20257,1,185,75.0,120.0,20.0,1,1,0,0,1,55.460643
6400,21287,19746,2,168,70.0,160.0,10.0,3,3,1,0,None,54.061602
7638,25442,15153,2,172,105.0,130.0,10.0,2,1,0,None,0,41.486653
7906,26367,20577,1,169,78.0,120.0,0.0,2,1,0,0,1,56.336756
8295,27649,19572,2,162,70.0,170.0,12.0,1,1,0,0,1,53.585216
11068,36953,23246,1,160,64.0,140.0,10.0,1,1,0,0,1,63.644079
13138,43735,23324,2,184,88.0,100.0,0.0,3,1,0,0,0,63.857632
13629,45450,18125,1,170,86.0,125.0,47.0,2,1,0,0,1,49.623546
15437,51515,20361,1,165,66.0,108.0,0.0,1,1,0,0,None,55.745380
17406,57993,19902,2,170,70.0,120.0,19.0,1,1,1,0,1,54.488706
18857,62837,19912,2,170,79.0,50.9,0.0,1,1,0,0,1,54.516085
20136,67171,21385,1,160,59.0,160.0,40.0,1,2,0,0,None,58.548939
24003,80247,16691,2,158,76.0,110.0,20.0,1,1,0,0,1,45.697467
24538,81975,20579,1,164,59.0,108.0,0.0,1,1,0,0,None,56.342231
25701,85793,18329,1,156,50.0,76.0,44.0,1,1,0,0,1,50.182067
25950,86648,20972,1,150,64.0,80.0,49.0,1,1,0,0,1,57.418207
26653,88937,20540,1,157,61.0,110.0,20.0,1,1,None,0,1,56.235455
29327,97796,21863,2,160,59.0,118.0,0.0,1,1,0,None,1,59.857632
29578,98631,19518,1,185,85.0,110.0,20.0,1,1,0,0,1,53.437372
29836,99499,20915,1,177,84.0,120.0,20.0,1,1,0,0,1,57.262149
29982,99929,21976,2,164,79.0,90.6,0.0,1,1,1,0,1,60.167009

In [11]:
train[train.weight < 40]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age2
3752,5306.0,15400.0,1.0,120.0,30.00,110.0,70.0,1.0,1.0,0.0,0.0,1.0,0.0,42.162902
5794,8226.0,17663.0,1.0,151.0,37.00,120.0,80.0,1.0,1.0,0.0,0.0,1.0,0.0,48.358658
10447,14908.0,22007.0,1.0,162.0,38.00,100.0,70.0,1.0,1.0,0.0,0.0,1.0,0.0,60.251882
10627,15182.0,21669.0,1.0,153.0,37.00,150.0,80.0,3.0,3.0,0.0,0.0,1.0,1.0,59.326489
11876,16963.0,17512.0,1.0,157.0,39.00,90.0,70.0,1.0,1.0,0.0,0.0,1.0,0.0,47.945243
14722,21040.0,22663.0,1.0,143.0,34.00,100.0,70.0,1.0,1.0,0.0,0.0,1.0,0.0,62.047912
16322,23318.0,21872.0,1.0,165.0,35.00,100.0,70.0,1.0,1.0,0.0,0.0,1.0,0.0,59.882272
16906,24167.0,17272.0,2.0,170.0,31.00,150.0,90.0,2.0,2.0,0.0,0.0,1.0,1.0,47.288159
18559,26503.0,18140.0,1.0,160.0,30.00,120.0,80.0,1.0,1.0,0.0,0.0,1.0,1.0,49.664613
19582,27965.0,21334.0,1.0,152.0,38.00,110.0,80.0,1.0,1.0,0.0,0.0,1.0,0.0,58.409309
22016,31439.0,15359.0,1.0,146.0,32.00,100.0,70.0,1.0,1.0,0.0,0.0,0.0,0.0,42.050650
25198,35972.0,18768.0,1.0,149.0,35.45,110.0,70.0,1.0,1.0,0.0,0.0,1.0,0.0,51.383984
26806,38312.0,23284.0,1.0,157.0,23.00,110.0,80.0,1.0,1.0,0.0,0.0,1.0,0.0,63.748118
29333,41919.0,21728.0,1.0,153.0,37.00,120.0,80.0,1.0,1.0,0.0,0.0,1.0,1.0,59.488022
29488,42156.0,20408.0,2.0,177.0,22.00,120.0,80.0,1.0,1.0,1.0,1.0,1.0,0.0,55.874059
31420,44852.0,20575.0,1.0,140.0,39.00,120.0,80.0,1.0,1.0,0.0,0.0,1.0,0.0,56.331280
32087,45814.0,15747.0,1.0,143.0,36.00,90.0,60.0,1.0,1.0,0.0,0.0,1.0,0.0,43.112936
33478,47830.0,15493.0,1.0,152.0,39.00,110.0,70.0,1.0,2.0,1.0,0.0,1.0,1.0,42.417522
33511,47872.0,21081.0,1.0,153.0,34.00,110.0,70.0,3.0,3.0,0.0,0.0,1.0,1.0,57.716632
33817,48318.0,21582.0,2.0,178.0,11.00,130.0,90.0,1.0,1.0,0.0,0.0,1.0,1.0,59.088296
33820,48322.0,22571.0,1.0,145.0,36.00,120.0,80.0,1.0,1.0,0.0,0.0,1.0,0.0,61.796030
34276,48976.0,14664.0,2.0,128.0,28.00,120.0,80.0,1.0,1.0,0.0,0.0,1.0,0.0,40.147844
34282,48985.0,20406.0,1.0,148.0,36.00,140.0,80.0,1.0,1.0,0.0,0.0,1.0,1.0,55.868583
34328,49043.0,14670.0,1.0,152.0,39.00,90.0,60.0,1.0,1.0,0.0,0.0,1.0,0.0,40.164271
35314,50443.0,19802.0,1.0,146.0,32.00,130.0,80.0,1.0,2.0,0.0,0.0,0.0,0.0,54.214921
38417,54851.0,21809.0,1.0,154.0,32.00,110.0,60.0,1.0,1.0,0.0,0.0,1.0,0.0,59.709788
38743,55311.0,21291.0,1.0,152.0,38.00,150.0,100.0,1.0,1.0,0.0,0.0,1.0,1.0,58.291581
40612,58033.0,23202.0,1.0,154.0,38.00,90.0,70.0,1.0,2.0,0.0,0.0,1.0,0.0,63.523614
41353,59092.0,20892.0,1.0,157.0,38.00,120.0,80.0,1.0,1.0,0.0,0.0,1.0,1.0,57.199179
41905,59853.0,21334.0,1.0,143.0,30.00,103.0,61.0,2.0,1.0,0.0,0.0,1.0,0.0,58.409309
43759,62529.0,18050.0,1.0,135.0,37.00,150.0,90.0,2.0,3.0,0.0,0.0,1.0,0.0,49.418207
44138,63056.0,21828.0,1.0,151.0,38.00,100.0,70.0,1.0,1.0,0.0,0.0,1.0,1.0,59.761807
44622,63728.0,18240.0,1.0,150.0,39.00,130.0,90.0,1.0,1.0,0.0,0.0,1.0,0.0,49.938398
48080,68667.0,19255.0,1.0,143.0,33.00,100.0,60.0,1.0,1.0,0.0,0.0,1.0,0.0,52.717317
48613,69417.0,20452.0,1.0,144.0,36.00,100.0,70.0,1.0,1.0,0.0,0.0,1.0,0.0,55.994524
51411,73318.0,21115.0,1.0,155.0,37.00,110.0,70.0,1.0,1.0,0.0,0.0,0.0,1.0,57.809719
51544,73511.0,21989.0,1.0,151.0,38.00,120.0,80.0,1.0,1.0,0.0,1.0,0.0,0.0,60.202601
51837,73914.0,19817.0,2.0,139.0,34.00,120.0,70.0,1.0,1.0,0.0,0.0,1.0,0.0,54.255989
53224,75927.0,20396.0,1.0,133.0,36.00,100.0,60.0,1.0,1.0,0.0,0.0,0.0,0.0,55.841205
53945,76956.0,22637.0,1.0,156.0,39.00,90.0,60.0,1.0,1.0,0.0,0.0,1.0,0.0,61.976728
54017,77054.0,22564.0,1.0,134.0,37.00,180.0,90.0,1.0,1.0,0.0,0.0,1.0,0.0,61.776865
54682,78012.0,20479.0,1.0,153.0,39.00,110.0,70.0,1.0,1.0,0.0,0.0,1.0,0.0,56.068446
55339,78940.0,23562.0,1.0,147.0,39.00,120.0,80.0,1.0,1.0,0.0,0.0,1.0,1.0,64.509240
55852,79686.0,23370.0,1.0,152.0,34.00,140.0,90.0,1.0,1.0,0.0,0.0,1.0,1.0,63.983573
56914,81240.0,18980.0,1.0,152.0,37.00,90.0,50.0,1.0,1.0,0.0,0.0,1.0,0.0,51.964408
57858,82567.0,18804.0,2.0,165.0,10.00,180.0,110.0,2.0,2.0,0.0,0.0,1.0,1.0,51.482546
58200,83048.0,22544.0,1.0,169.0,35.00,140.0,90.0,2.0,1.0,0.0,0.0,1.0,1.0,61.722108
60188,85931.0,21855.0,1.0,162.0,21.00,120.0,80.0,2.0,1.0,0.0,0.0,1.0,1.0,59.835729
60699,86650.0,18875.0,1.0,171.0,29.00,110.0,70.0,2.0,1.0,0.0,0.0,1.0,1.0,51.676934
63113,90128.0,20406.0,1.0,158.0,39.00,90.0,60.0,1.0,1.0,0.0,0.0,0.0,1.0,55.868583
65082,92896.0,22688.0,1.0,145.0,33.00,130.0,100.0,2.0,1.0,0.0,0.0,1.0,1.0,62.116359
65650,93697.0,19114.0,1.0,147.0,38.00,100.0,70.0,3.0,3.0,0.0,0.0,1.0,0.0,52.331280

In [12]:
test[test.weight < 40]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,age2
259,854,15187,2,183,13.0,120.0,80.0,1,1,0,1,1,41.579740
2317,7812,19785,1,157,10.0,120.0,80.0,1,1,0,0,1,54.168378
2905,9732,19687,1,130,30.0,120.0,80.0,1,1,0,0,1,53.900068
4413,14741,21301,1,159,38.0,100.0,80.0,1,1,0,0,1,58.318960
4721,15674,18377,1,147,34.0,100.0,60.0,1,1,0,0,1,50.313484
6148,20501,18380,1,144,35.0,120.0,80.0,1,1,0,0,0,50.321697
8005,26707,22645,1,162,38.0,110.0,80.0,2,2,0,0,1,61.998631
9315,31072,20670,1,165,32.0,120.0,80.0,3,3,None,0,None,56.591376
9339,31144,21845,1,147,37.0,110.0,70.0,3,3,0,0,1,59.808350
12479,41584,23388,1,148,39.0,110.0,60.0,2,2,0,0,1,64.032854
13830,46128,18808,1,151,37.0,120.0,80.0,3,1,0,0,1,51.493498
15334,51141,20598,1,145,35.0,120.0,80.0,2,1,0,0,1,56.394251
16349,54609,16018,1,169,16.3,130.0,80.0,1,1,0,None,0,43.854894
16704,55762,17546,1,150,31.0,120.0,70.0,1,1,0,None,1,48.038330
17350,57796,23420,1,156,39.0,140.0,90.0,3,1,0,0,1,64.120465
17418,58027,14848,2,170,20.0,120.0,80.0,1,1,0,0,0,40.651608
20113,67077,22040,2,159,37.0,100.0,80.0,1,1,1,0,1,60.342231
20786,69364,23227,1,127,30.0,120.0,70.0,3,1,0,0,None,63.592060
20790,69373,17417,1,147,35.0,110.0,70.0,1,1,0,0,1,47.685147
21748,72730,16096,1,146,38.0,100.0,60.0,1,1,0,0,1,44.068446
23395,78213,20314,2,134,38.0,120.0,80.0,1,1,0,None,0,55.616701
25555,85292,22046,1,149,39.0,120.0,80.0,2,1,0,0,0,60.358658
27372,91387,16044,1,158,38.0,130.0,90.0,1,1,0,0,1,43.926078
28159,94038,20443,1,174,32.0,120.0,80.0,1,1,0,0,1,55.969884
28227,94256,23359,1,160,38.0,100.0,60.0,1,1,0,0,0,63.953457
28825,96186,19026,1,169,10.0,120.0,80.0,1,1,0,None,1,52.090349
29991,99976,20327,2,168,38.0,120.0,80.0,1,1,0,0,1,55.652293

In [19]:
train.height.describe(), test.height.describe()

(count    69978.000000
 mean       164.394167
 std          8.015450
 min         91.000000
 25%        159.000000
 50%        165.000000
 75%        170.000000
 max        250.000000
 Name: height, dtype: float64, count    30000.000000
 mean       164.362267
 std          7.956004
 min        100.000000
 25%        159.000000
 50%        165.000000
 75%        170.000000
 max        198.000000
 Name: height, dtype: float64)

In [14]:
train[train.height <= 100]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age2
3420,4838.0,14516.0,1.0,100.0,70.0,100.0,70.0,1.0,1.0,0.0,0.0,1.0,0.0,39.742642
8171,11662.0,17646.0,2.0,97.0,170.0,160.0,100.0,1.0,1.0,1.0,0.0,1.0,1.0,48.312115
17074,24396.0,21259.0,1.0,100.0,86.0,110.0,70.0,1.0,1.0,0.0,0.0,1.0,1.0,58.203970
17277,24690.0,17530.0,1.0,98.0,45.0,120.0,80.0,1.0,1.0,0.0,0.0,1.0,0.0,47.994524
28737,41075.0,19747.0,1.0,91.0,55.0,140.0,90.0,1.0,1.0,0.0,0.0,1.0,1.0,54.064339
56022,79917.0,21171.0,1.0,96.0,59.0,90.0,60.0,1.0,1.0,0.0,0.0,1.0,1.0,57.963039
58868,84021.0,14680.0,2.0,100.0,60.0,100.0,60.0,1.0,1.0,0.0,0.0,1.0,0.0,40.191650
65302,93223.0,18467.0,1.0,99.0,60.0,90.0,60.0,1.0,1.0,0.0,0.0,1.0,0.0,50.559890

In [15]:
test[test.height <= 100]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,age2
3089,10347,19681,1,100,70.0,100.0,70.0,2,1,0,None,1,53.883641

In [17]:
train[train.height > 200]

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age2
6486,9223.0,21220.0,1.0,250.0,86.0,140.0,100.0,3.0,1.0,0.0,0.0,1.0,1.0,58.097194
21628,30894.0,19054.0,2.0,207.0,78.0,100.0,70.0,1.0,1.0,0.0,1.0,1.0,0.0,52.167009